chore(tools): bump to TypeScript 6 and TypeDoc 0.28.19 (#45370)
# Why

Running `et generate-docs-api-data --packageName expo-router` was
failing with the following error message:

```
error TS5095: Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.
```

# How

Bumped `typescript` to `^6.0.3` and `typedoc` to `^0.28.19` in
`tools/package.json`.

# Test Plan

- CI
- Run `et generate-docs-api-data --packageName expo-router`

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)