[iOS][core] Fix double to UIColor conversion (#45387)
# Why
fixes the calendar@next errors from the QA:
```
[FAIL] Calendar@next Global functions listEvents() returns an array of events
Error: The 1st argument cannot be cast to type CalendarRecordNext
→ Caused by: Cannot cast '4283143818.0' for field 'color' of type Optional<UIColor>
→ Caused by: Cannot convert 'Optional(Optional(4283143818.0))' to UIColor
```


# How
Adds a conversion from double to UIColor to `Convertibles+Color.swift`

# Test Plan

Added a native test